version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trainingdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    ports:
      - "3306:3306" # utile si tu veux te connecter depuis un client externe
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ../backend
    container_name: training-api
    environment:
      DB_HOST: mysql
      DB_USER: app
      DB_PASSWORD: app123
      DB_NAME: trainingdb
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    # (optionnel) restart: unless-stopped

  frontend:
    build:
      context: ../frontend
    container_name: training-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
